extends: eslint-config-dmitmel/presets/node
env:
  browser: true
plugins: ['prettier']

settings:
  node:
    tryExtensions: ['.tsx', '.ts', '.jsx', '.js', '.json', '.node']

globals:
  hh: writable
  magicrequire: writable
  DiscordNative: writable

rules:
  prettier/prettier:
    - error
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules

overrides:
  - files: '**/*.ts*'
    extends:
      - eslint-config-dmitmel/presets/typescript-addon
    parserOptions:
      ecmaVersion: 2020
      project: 'tsconfig.json'
      sourceType: module
    rules:
      eqeqeq: 0
      require-await: 0
      no-undefined: 0

      # the only reason this is allowed is because there's no easy way to make it shut up about the custom imports
      'node/no-missing-import': 0

      '@typescript-eslint/no-dynamic-delete': 0
      '@typescript-eslint/no-explicit-any': 0
      '@typescript-eslint/no-non-null-asserted-optional-chain': 0
      '@typescript-eslint/naming-convention': 0
